### ISSUE TITLE
Drop-down menu for "purpose" field 

### ISSUE THREAD

**Issue by klcummings** [UGS-GIS/UCRC---Survey-123#11]
### What type of GIS Support?

Data collection app

### Describe the support you requested.

Can we add a drop-down menu for the "purpose" field in the drill hole list table?  

The options should include:
oil and gas
mining
coal 
building or construction
tar sands
oil shale
potash
stratigraphy
geothermal
water
teaching
exploration
unknown

### When is this GIS support needed by...

n/a

### How Urgent is this?

Medium

### Please list Project Code to charge time.

n/a

**Comment by marthajensen** [comment]
added
