### ISSUE TITLE
additional item listed in the purpose field dropdown

### ISSUE THREAD

**Issue by klcummings** [UGS-GIS/UCRC---Survey-123#13]
### What GIS product are you requesting?

General GIS work

### Check all that apply

- [ ] ArcMap
- [ ] ArcGIS Pro
- [ ] This is a StateMap Project

### Describe your requested GIS product.

Can 'brine' be added to the purpose field dropdown list? 

### When is this GIS product needed?

NA

### How Urgent is this?

Medium

### Where is existing GIS, map and/or supporting info currently stored?

NA

### Where to save new GIS product?

NA

**Comment by marthajensen** [comment]
done
