### ISSUE TITLE
Additional field in the Drill Hole list table 

### ISSUE THREAD

**Issue by klcummings** [UGS-GIS/UCRC---Survey-123#14]
### What GIS product are you requesting?

Edit new/existing GIS data

### Check all that apply

- [ ] ArcMap
- [ ] ArcGIS Pro
- [ ] This is a StateMap Project

### Describe your requested GIS product.

Can a field for 'mining_district' be added after 'field_name' in the Drill Hole list? 

### When is this GIS product needed?

NA

### How Urgent is this?

Medium

### Where is existing GIS, map and/or supporting info currently stored?

NA

### Where to save new GIS product?

NA

**Comment by marthajensen** [comment]
New field added. You'll need to refresh/reload the map on the Ipad to see it
