### ISSUE TITLE
UCRC Inventory Survey - New Field?

### ISSUE THREAD

**Issue by klcummings** [UGS-GIS/UCRC---Survey-123#3]
### What GIS product are you requesting?

Edit new/existing GIS data

### Check all that apply

- [X] ArcMap
- [ ] ArcGIS Pro
- [ ] This is a StateMap Project

### Describe your requested GIS product.

Can we add a new alphanumeric column in the box inventory table named "core_number"? Maybe adjacent to the box_bottom_depth column? Typically, oil and gas wells have multiple cores for each well (i.e., core 1 8000-8090', core 2 9050-10070', etc), and each core has it's own set of boxes (i.e., core 1 boxes 1-12, core 2 boxes 1-8, etc). I'd still like to record a running box number (i.e., boxes 1-180), but would also like to record core number and respective box number (i.e., core 1 box 1, core 2 box 1, etc). 

### When is this GIS product needed?

11/1/2022

### How Urgent is this?

Medium

### Where is existing GIS, map and/or supporting info currently stored?

UCRC_Inventory_Survey

### Where to save new GIS product?

UCRC_Inventory_Survey

### Please list Project Code to charge time.

UEXO

**Comment by marthajensen** [comment]
new field added
