### ISSUE TITLE
UCRC Inventory Survey - ground_elevation data

### ISSUE THREAD

**Issue by klcummings** [UGS-GIS/UCRC---Survey-123#5]
### What type of GIS Support?

Data collection app

### Describe the support you requested.

We are unable to enter 'ground_elevation' information when entering a new record. 

### When is this GIS support needed by...

11/1/2022

### How Urgent is this?

Medium

### Please list Project Code to charge time.

UEXO

**Comment by marthajensen** [comment]
Ground elevation was hidden - sorry about that. It should be fixed now. I also added a notation for feet (ft) in the field caption. I think the data is in feet, but if its in meters instead, let me know and I'll change that.
