### ISSUE TITLE
UCRC Inventory Survey - e notation for shelf locations with an 'E'

### ISSUE THREAD

**Issue by klcummings** [UGS-GIS/UCRC---Survey-123#6]
### What type of GIS Support?

Data collection app

### Describe the support you requested.

It appears that shelf locations with an 'E' (i.e., 17E6) are changed to e notation in the database. Is there another workaround other than adding hypens to shelf locations? 

### When is this GIS support needed by...

11/1/2022

### How Urgent is this?

Low

### Please list Project Code to charge time.

UEXO

**Comment by marthajensen** [comment]
Hi Katie - I fixed all of the E notations for the most part. It was a data import issue with the CSV except api - 4303731145. It appears that api had a weird E notation in the original xlsx.
