### ISSUE TITLE
UCRC Inventory Survey - keywords 

### ISSUE THREAD

**Issue by klcummings** [UGS-GIS/UCRC---Survey-123#7]
### What type of GIS Support?

Data collection app

### Describe the support you requested.

Can the keyword hints be changed to 'lacustrine', 'sandstone', 'Dugway'? 

### When is this GIS support needed by...

11/1/2022

### How Urgent is this?

Low

### Please list Project Code to charge time.

UEXO

**Comment by marthajensen** [comment]
Keywords changed. If on Ipad, please re-download the Survey. On my Ipad, I wasn't able to update the Survey I have been using up until now. Instead the Ipad downloaded a totally new one and I had to delete the old Survey.
