### ISSUE TITLE
Box Inventory table sample_types different than Survey 123 drop-down list of sample types

### ISSUE THREAD

**Issue by marthajensen** [UGS-GIS/UCRC---Survey-123#9]
### What type of GIS Support?

Data collection app

### Describe the support you requested.

Hi Katie,

I noticed that there are differences between the types of core samples provided for Survey 123 and the types of core samples that already exist in the sample_types field  in the database. In order to make the drop-down list for that field consistent with the database, I am proposing these changes:

1. Make all values in sample_type field lowercase (instead of camel-case) to match the sample list, which are all lowercase (I already did this)
2. Existing value "slabs" should be changed to "core slabs" to match rest of list
3. Add "collection" to the sample list
4. Existing value "display" should be changed to "display samples"
5. Existing value "sidewall" should be changed to "sidewall core" to match rest of list
6. Existing value "samples" should be changed to "sample" to match rest of list

**_Please let me know if you approve these changes._** 

If you would like the list of choices in Survey 123 to be changed instead of the sample_types that already exist in the database, let me know. 

Below is the list given to me that I added to Survey 123:

core
core slabs
core butts
skeletonized core
split core
chips
core chips
cuttings
plugs
plug ends
sidewall core
discontinuous core
discontinuous slabs
discontinuous butts
discontinuous split core
rubble
outcrop samples
hand samples
crushed samples
powdered samples
display samples
donated collection
oil samples
conodonts
trim ends
sample
unknown

### When is this GIS support needed by...

n/a

### How Urgent is this?

Medium

### Please list Project Code to charge time.

n/a

**Comment by klcummings** [comment]
Martha, 

I'm fine with the suggested changes. Do you plan to make the changes? Or do you need anything from me? 

Thanks.
Katie

**Comment by marthajensen** [comment]
I'll make the changes

**Comment by marthajensen** [comment]
completed
